### ISSUE TITLE
Sortie intempestive

### ISSUE THREAD

**Issue by Beltrando** [CocoaBob/PebbleTransilien#3]
Sur Steel
Pré-requis : 
1) Avoir le problème "mémoire insuffisante" du ticket #2  
2) Avoir un favori "Grigny centre"
3) L'application est en raccourci 

Scenario: 
1) lancer l'app par le raccourci (clic sur le bouton haut prolongé) => l'App s'affiche
2) Cliquer sur le favori "Grigny Centre" => les premiers trains s'affichent
3) cliquer deux fois sur "bouton bas" pour aller chercher le détail d'un train => sortie intempestive de l'App et retour à la liste des App.

**Comment by CocoaBob** [comment]
Hi,

Thank you for your reporting! I just tried it in the simulator, yes, there's not enough memory.

I didn't anticipate that the Next Trains list could be so long for the station "Grigny Centre"! So we need to limit the number of rows displayed in the list, to reduce memory cost.

I will check it as soon as possible :)

**Comment by Beltrando** [comment]
... et bonne année!

**Comment by CocoaBob** [comment]
Hi, 
Version 1.5 has just been released, I've limited the number of next trains to avoid consuming too much memory. I think it should solve the problem you've met for the stations "Ris-Orangis" and "Grigny Centre", please test if you have time :)
Thank you for your supporting!
