### ISSUE TITLE
Message "mémoire insuffisante"

### ISSUE THREAD

**Issue by Beltrando** [CocoaBob/PebbleTransilien#4]
99% de chances que ce soit la même cause que le #3 mais c'est pas à moi d'en juger, donc:

Sur Steel
Pré-requis : 
1) Avoir le problème "mémoire insuffisante" du ticket #2
2) Avoir un favori "Ris-Orangis"
3) L'application est en raccourci
4) Au total il y a 4 raccourcis dans l'App
5) Au total 10 applications installées sur la Steel, dont un GPS.

Scenario: 
1) lancer l'app par le raccourci (clic sur le bouton haut prolongé) => l'App s'affiche
2) Cliquer sur le favori "Ris-Orangis" => les premiers trains s'affichent
3) cliquer deux fois sur "bouton bas" pour aller chercher le détail d'un train => Message d'erreur clignotant "Mémoire insuffisante". Et on reste sur le même écran: on peut se déplacer sur la liste des trains, revenir en arrière et relancer la recherche du favori sans problème

**Comment by CocoaBob** [comment]
Oh, another station.

Yes, it's the same problem as #3 I'm going to limit the Next Trains list to reduce memory cost.

Fortunately we can hide some future trains in the Next Trains list on the 2nd window. But if Stations list on the 3rd window is too long, I've no idea for the moment, it will crash I suppose...

Let me think about that, maybe more features should be removed for 24KB devices...

By the way, no matter how many apps are installed on your Steel, the available running memory for each app is always 24KB. So feel free to install more apps :)

**Comment by Beltrando** [comment]
Merci!

**Comment by CocoaBob** [comment]
Hi, 
Version 1.5 has just been released, I've limited the number of next trains to avoid consuming too much memory. I think it should solve the problem you've met for the stations "Ris-Orangis" and "Grigny Centre", please test if you have time :)
Thank you for your supporting!

**Comment by Beltrando** [comment]
Je confirme: tout est ok. Merci.
